### ISSUE TITLE
OffChat and RetailStore demo projects do not work in TPL 7.7.0

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#223]
When importing and build demo projects in 7.7.0 and set TPL to 7.7.0, have the following build error:

> Error
Close
Typescript Error
Module '"D:/COMMON/C8O/sc770_64/workspace/sampleMobileOffChat/_private/ionic/node_modules/c8osdkangular/src/index"' has no exported member 'C8oNetworkStatus'.
...O/sc770_64/workspace/sampleMobileOffChat/_private/ionic/src/app/app.component.ts
import { C8o, C8oSettings, C8oLogLevel,C8oProgress }        from "c8osdkangular";
import { C8oNetworkStatus }                                 from "c8osdkangular";
Typescript Error
Property 'setKeepSessionAlive' does not exist on type 'C8oSettings'.
...O/sc770_64/workspace/sampleMobileOffChat/_private/ionic/src/app/app.component.ts
    .setLogLevelLocal(C8oLogLevel.DEBUG)
    .setKeepSessionAlive(true);
/*Begin_c8o_AppSettings*/
Typescript Error
Module '"D:/COMMON/C8O/sc770_64/workspace/sampleMobileOffChat/_private/ionic/node_modules/c8osdkangular/src/index"' has no exported member 'C8oNetworkStatus'.
...C8O/sc770_64/workspace/sampleMobileOffChat/_private/ionic/src/pages/Chat/chat.ts
		 C8oCafUtils }                      										from 'c8ocaf';
import { C8oNetworkStatus }                                 						from 'c8osdkangular';
import { ChangeDetectorRef,
Typescript Error
Module '"D:/COMMON/C8O/sc770_64/workspace/sampleMobileOffChat/_private/ionic/node_modules/c8osdkangular/src/index"' has no exported member 'C8oNetworkStatus'.
...O/sc770_64/workspace/sampleMobileOffChat/_private/ionic/src/pages/Lobby/lobby.ts
		 C8oCafUtils }                      										from 'c8ocaf';
import { C8oNetworkStatus }                                 						from 'c8osdkangular';
import { ChangeDetectorRef,
Typescript Error
Module '"D:/COMMON/C8O/sc770_64/workspace/sampleMobileOffChat/_private/ionic/node_modules/c8osdkangular/src/index"' has no exported member 'C8oNetworkStatus'.
...O/sc770_64/workspace/sampleMobileOffChat/_private/ionic/src/pages/Login/login.ts
		 C8oCafUtils }                      										from 'c8ocaf';
import { C8oNetworkStatus }                                 						from 'c8osdkangular';
import { ChangeDetectorRef,
Typescript Error
Module '"D:/COMMON/C8O/sc770_64/workspace/sampleMobileOffChat/_private/ionic/node_modules/c8osdkangular/src/index"' has no exported member 'C8oNetworkStatus'.
...C8O/sc770_64/workspace/sampleMobileOffChat/_private/ionic/src/pages/Sync/sync.ts
		 C8oCafUtils }                      										from 'c8ocaf';
import { C8oNetworkStatus }                                 						from 'c8osdkangular';
import { ChangeDetectorRef,
Ionic Framework: 3.9.5
Ionic App Scripts: 3.1.9
Angular Core: 5.2.11
Angular Compiler CLI: 5.2.11
Node: 8.9.1
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Android

![image](https://user-images.githubusercontent.com/1685373/66643382-dcda9f80-ec1e-11e9-85f6-21f19e723a0b.png)

**Comment by nathalie-lammelin** [comment]
@gregory-vorbe : **Not Reproduced**
Using a dev Studio, followed below steps :
1 - File>New project...>Convertigo Samples & Demos>**OffChat**, next, finish
2 - Keep original `7.5.2` tpl, `Execute` app : OK in MB, no error
3 - Change to `7.6.0` tpl, `save & reload` project, `Reinstall packages & Execute` : OK in MB, no error
4 - Change to `7.7.0` tpl, `save & reload` project, `Reinstall packages & Execute` : OK in MB, no error

Idem with the **RetailStore** project : everything is ok.
All tests done with a `7.6.5` Studio and a `7.7.0` Studio.

=> Thus, I suppose you didn't `Reinstall packages & Execute` : let me know

While testing the **IonicConferenceApp**, I had error in app.component.ts for routes generation.
I'll fix that.

**Comment by gregory-vorbe** [comment]
Following your steps, it is effectively correctly working. I must have missed the `Re-install packages and Execute` part when I changed TPL version.
